const LOCALES = ["en", "zh-tw", "zh-cn"];

const CONTENT = {
  en: {
    languageLabel: "EN",
    title: "LeiMai Throne | Proof-of-Wealth Support Arena",
    description:
      "Claim the LeiMai Throne by highest single verified USDT (TRC20) transfer. Public leaderboard, moderated declarations, and compliance-first support flow.",
    keywords:
      "LeiMai Throne,LeiMai Oracle,support leaderboard,USDT TRC20,proof of wealth,crypto supporter wall",
    brandSub: "Proof-of-Wealth Support Arena",
    heroTag: "APEX THRONE PROTOCOL",
    heroHeadline: "ONE VERIFIED TRANSFER CAN REWRITE THE ORDER.",
    heroSub:
      "Every transfer is a public signal. Highest single verified USDT transfer owns the active throne until replaced.",
    liveSyncText: "Dual-source sync active.",
    sourceLabel: "Verification Mesh",
    sourceDualLive: "Tronscan + TronGrid online",
    sourceLimited: "Single source fallback",
    syncLabel: "Last Sync (UTC)",
    refreshInLabel: "Next Refresh",
    minRankLabel: "Ranking Floor",
    ctaSupport: "Enter Support Channel",
    ctaClaim: "Submit Declaration",
    ctaMain: "Open LeiMai Oracle Pro/Elite",
    kingTitle: "Current Throne Holder",
    leaderboardTitle: "Top 10 Verified Single Transfers",
    declarationTitle: "Declaration Console",
    statusTitle: "Declaration Status",
    policyTitle: "Policy and Compliance",
    policy1: "This property is for support and public signaling only. It is not investment advice.",
    policy2: "No guaranteed return, no asset custody, no solicitation of financial products.",
    policy3: "All declarations are pre-moderated before publication.",
    amountLabel: "Single Transfer",
    walletLabel: "Wallet",
    timeLabel: "Confirmed UTC",
    rankLabel: "Rank",
    txLabel: "Tx Hash",
    noKing: "No verified throne holder yet.",
    noAds: "No approved ads yet.",
    declarationPlaceholder: "Write your declaration or ad line (8-280 chars) ...",
    submitText: "Send for Moderation",
    statusPlaceholder: "Declaration ID",
    checkStatusText: "Check Status",
    paymentTitle: "USDT (TRC20) Support Address",
    copyAddress: "Copy Address",
    copied: "Copied",
    copyFailed: "Copy failed",
    faqTitle: "FAQ",
    faq1q: "How is rank decided?",
    faq1a: "Highest single verified transfer wins. If tied, earlier confirmation time wins.",
    faq2q: "Can the throne be replaced?",
    faq2a: "Yes. Any higher verified single transfer immediately replaces the current throne holder.",
    faq3q: "Why pre-moderation?",
    faq3a: "To keep legal, policy, and readability standards for a public support property.",
    adsTitle: "Approved Declaration Ads",
    pendingText: "Pending moderation",
    approvedText: "Approved",
    rejectedText: "Rejected",
    throneReplacedText: "THRONE REPLACED",
    loadErrorText: "Live update interrupted",
    footer:
      "LeiMai Throne is an independent support property linked to LeiMai Oracle. No investment advice.",
  },
  "zh-tw": {
    languageLabel: "繁中",
    title: "LeiMai Throne | 財力證明支持場",
    description:
      "用單筆最高且已驗證的 USDT(TRC20) 轉帳爭奪 LeiMai Throne。公開排行、宣言審核、合規優先的支持流程。",
    keywords:
      "LeiMai Throne,LeiMai Oracle,支持排行榜,USDT TRC20,財力證明,加密支持牆",
    brandSub: "財力證明支持場",
    heroTag: "APEX THRONE 協定",
    heroHeadline: "一筆已驗證轉帳，就能改寫席次。",
    heroSub:
      "每筆轉帳都是公開訊號。單筆最高且已驗證的 USDT 轉帳，成為當前王座持有者，直到被更高金額取代。",
    liveSyncText: "雙來源同步中。",
    sourceLabel: "驗證網格",
    sourceDualLive: "Tronscan + TronGrid 上線",
    sourceLimited: "單來源降級",
    syncLabel: "最近同步 (UTC)",
    refreshInLabel: "下次刷新",
    minRankLabel: "入榜門檻",
    ctaSupport: "進入支持通道",
    ctaClaim: "提交宣言",
    ctaMain: "開啟 LeiMai Oracle Pro/Elite",
    kingTitle: "當前王座持有者",
    leaderboardTitle: "已驗證單筆轉帳 Top 10",
    declarationTitle: "宣言主控台",
    statusTitle: "宣言狀態",
    policyTitle: "政策與合規",
    policy1: "本站僅用於支持與公開身分訊號，不構成投資建議。",
    policy2: "不保證回報、不保管資產、不提供金融商品招攬。",
    policy3: "所有宣言皆需先審核，通過後才公開。",
    amountLabel: "單筆金額",
    walletLabel: "錢包",
    timeLabel: "確認時間 UTC",
    rankLabel: "排名",
    txLabel: "交易雜湊",
    noKing: "目前尚無已驗證王座持有者。",
    noAds: "目前尚無通過審核的廣告。",
    declarationPlaceholder: "輸入你的宣言或廣告文案（8-280 字）...",
    submitText: "送交審核",
    statusPlaceholder: "宣言 ID",
    checkStatusText: "查詢狀態",
    paymentTitle: "USDT (TRC20) 支持地址",
    copyAddress: "複製地址",
    copied: "已複製",
    copyFailed: "複製失敗",
    faqTitle: "常見問題",
    faq1q: "排名如何決定？",
    faq1a: "以單筆已驗證轉帳金額最高者為先；若金額相同，較早確認者優先。",
    faq2q: "王座可以被取代嗎？",
    faq2a: "可以。任何更高且已驗證的單筆轉帳，都會即時取代現任王座。",
    faq3q: "為什麼要先審核？",
    faq3a: "為維持法規、平台政策與公開可讀性，宣言需先審核再發佈。",
    adsTitle: "已核准宣言廣告",
    pendingText: "審核中",
    approvedText: "已通過",
    rejectedText: "未通過",
    throneReplacedText: "王座已被改寫",
    loadErrorText: "即時更新中斷",
    footer:
      "LeiMai Throne 為獨立支持站，與 LeiMai Oracle 互通導流。本站不提供投資建議。",
  },
  "zh-cn": {
    languageLabel: "简中",
    title: "LeiMai Throne | 财力证明支持场",
    description:
      "用单笔最高且已验证的 USDT(TRC20) 转账争夺 LeiMai Throne。公开排行、宣言审核、合规优先的支持流程。",
    keywords:
      "LeiMai Throne,LeiMai Oracle,支持排行榜,USDT TRC20,财力证明,加密支持墙",
    brandSub: "财力证明支持场",
    heroTag: "APEX THRONE 协议",
    heroHeadline: "一笔已验证转账，就能改写席位。",
    heroSub:
      "每笔转账都是公开信号。单笔最高且已验证的 USDT 转账成为当前王座持有者，直到被更高金额取代。",
    liveSyncText: "双来源同步中。",
    sourceLabel: "验证网格",
    sourceDualLive: "Tronscan + TronGrid 在线",
    sourceLimited: "单来源降级",
    syncLabel: "最近同步 (UTC)",
    refreshInLabel: "下次刷新",
    minRankLabel: "入榜门槛",
    ctaSupport: "进入支持通道",
    ctaClaim: "提交宣言",
    ctaMain: "打开 LeiMai Oracle Pro/Elite",
    kingTitle: "当前王座持有者",
    leaderboardTitle: "已验证单笔转账 Top 10",
    declarationTitle: "宣言控制台",
    statusTitle: "宣言状态",
    policyTitle: "政策与合规",
    policy1: "本站仅用于支持与公开身份信号，不构成投资建议。",
    policy2: "不保证回报、不托管资产、不提供金融产品招揽。",
    policy3: "所有宣言均需预审，通过后才公开。",
    amountLabel: "单笔金额",
    walletLabel: "钱包",
    timeLabel: "确认时间 UTC",
    rankLabel: "排名",
    txLabel: "交易哈希",
    noKing: "当前暂无已验证王座持有者。",
    noAds: "当前暂无通过审核的广告。",
    declarationPlaceholder: "输入你的宣言或广告文案（8-280 字）...",
    submitText: "提交审核",
    statusPlaceholder: "宣言 ID",
    checkStatusText: "查询状态",
    paymentTitle: "USDT (TRC20) 支持地址",
    copyAddress: "复制地址",
    copied: "已复制",
    copyFailed: "复制失败",
    faqTitle: "常见问题",
    faq1q: "排名如何决定？",
    faq1a: "以单笔已验证转账金额最高者优先；若金额相同，较早确认者优先。",
    faq2q: "王座可以被取代吗？",
    faq2a: "可以。任何更高且已验证的单笔转账都会即时替换当前王座持有者。",
    faq3q: "为什么要预审？",
    faq3a: "为维持法规、平台政策与公开可读性，宣言需要先审核后发布。",
    adsTitle: "已批准宣言广告",
    pendingText: "审核中",
    approvedText: "已通过",
    rejectedText: "未通过",
    throneReplacedText: "王座已被改写",
    loadErrorText: "实时更新中断",
    footer:
      "LeiMai Throne 为独立支持站，与 LeiMai Oracle 互通导流。本站不提供投资建议。",
  },
};

export function resolveLocale(value) {
  const input = String(value || "").toLowerCase();
  if (LOCALES.includes(input)) return input;
  return "en";
}

export function getContent(locale) {
  return CONTENT[resolveLocale(locale)];
}

export function getHreflangUrls(baseUrl) {
  const root = baseUrl.replace(/\/+$/, "");
  return [
    { locale: "en", href: `${root}/en`, hreflang: "en" },
    { locale: "zh-tw", href: `${root}/zh-tw`, hreflang: "zh-Hant" },
    { locale: "zh-cn", href: `${root}/zh-cn`, hreflang: "zh-Hans" },
    { locale: "x-default", href: `${root}/en`, hreflang: "x-default" },
  ];
}

export function listLocales() {
  return [...LOCALES];
}
