const COMMON_KEYWORDS =
  "Sovereign AI Oracle, BTC Alpha Signals, Whale Intelligence, Institutional Crypto Analysis";

const COPY = {
  en: {
    keywords: COMMON_KEYWORDS,
    paywallNotice:
      "This intelligence snapshot is protected by the LeiMai Sovereign Protocol. Sign with a cold wallet to unlock the full alpha record.",
    homeKicker: "LEIMAI ORACLE / SOVEREIGN CORE",
    homeTitle: "Sovereign Intelligence Wall",
    homeLead:
      "Institution-grade market intelligence stream with conclusion-first narratives and strict risk context.",
    homeOpenIndex: "Open Full Intelligence Index",
    homeMainDomain: "Main Domain",
    homeLatestTitle: "Latest 5 Sovereign Briefs",
    homeLatestLead: "Protocol Integrity: Sovereign Verified.",
    homeEmpty: "No public intelligence snapshots available in this cycle.",
    vaultKicker: "VAULT PREHEAT",
    vaultTitle: "Obsidian Vault",
    vaultLead: "Sovereign trading model is calibrating. Access is restricted to protocol signers.",
    backRoot: "Back to Root",
    backIndex: "Intelligence Matrix",
    gateSigned: "Waiting for Model Synced",
    gateUnsigned: "Sovereign Trading Model: Calibrating. Access Restricted to Protocol Signers.",
    sessionVerified: "SESSION VERIFIED",
    upgradeBtn: "[ UPGRADE TO SOVEREIGN ]",
    signBtn: "[ SIGN OUROBOROS CONTRACT ]",
    analysisKicker: "INTELLIGENCE INDEX",
    analysisTitle: "Sovereign Analysis Matrix",
    analysisLead: "Dynamic multilingual intelligence pages for high-intent market participants.",
    analysisSearch: "Filter: language / entity / title",
    analysisAllTitle: "All Intelligence Pages",
    analysisTotal: "Current total",
    analysisEmpty: "No intelligence records available yet.",
    detailKicker: "INTELLIGENCE DETAIL",
    detailBack: "Back to Index",
    detailMetaTitle: "Sovereign Metadata",
    detailMetaEvent: "Event",
    detailMetaLocale: "Language",
    detailMetaEntity: "Unique Entity",
    detailMetaUpdated: "Updated (UTC)",
    detailMetaAccess: "Access",
    detailLocked: "LOCKED",
    detailUnlocked: "UNLOCKED",
    detailPreviewTitle: "Intelligence Preview (20%)",
    detailFullTitle: "Full Intelligence Record",
    detailPolicyPublic: "Access policy: public preview tier.",
    detailPolicySigned: "Access policy: signed sovereign session.",
    detailStructuredTitle: "GEO Structured Payload",
    detailStructuredLead: "Embedded in head for compliant machine-readable indexing.",
    notFoundTitle: "Analysis page not found",
    notFoundLead: "No intelligence page matched this identifier.",
    notFoundBack: "Back to index",
    goneTitle: "Legacy route removed",
    goneLead: "This path has been permanently decommissioned.",
    goneRoot: "Go to root",
    goneIndex: "Intelligence matrix",
  },
  "zh-tw": {
    keywords: COMMON_KEYWORDS,
    paywallNotice: "此情報快照受 LeiMai 主權協議保護。請以冷錢包簽署以解鎖完整 Alpha 記錄。",
    homeKicker: "LEIMAI ORACLE / 主權核心",
    homeTitle: "主權情報牆",
    homeLead: "機構級市場情報流，以結論先行、風險邊界清晰為原則。",
    homeOpenIndex: "開啟完整情報索引",
    homeMainDomain: "主網域",
    homeLatestTitle: "最新 5 筆主權簡報",
    homeLatestLead: "協議完整性：主權已驗證。",
    homeEmpty: "本輪週期尚無可公開情報快照。",
    vaultKicker: "金庫預熱",
    vaultTitle: "曜石金庫",
    vaultLead: "主權交易模型校準中。僅限協議簽署者進入。",
    backRoot: "返回根頁",
    backIndex: "情報矩陣",
    gateSigned: "等待模型同步",
    gateUnsigned: "主權交易模型校準中。僅限協議簽署者進入。",
    sessionVerified: "簽署會話已驗證",
    upgradeBtn: "[ 升級為主權級別 ]",
    signBtn: "[ 簽署銜尾蛇協議 ]",
    analysisKicker: "情報索引",
    analysisTitle: "主權分析矩陣",
    analysisLead: "為高意向市場參與者生成的多語情報頁面。",
    analysisSearch: "篩選：語言 / 實體 / 標題",
    analysisAllTitle: "全部情報頁面",
    analysisTotal: "當前總量",
    analysisEmpty: "目前尚無情報記錄。",
    detailKicker: "情報詳頁",
    detailBack: "返回索引",
    detailMetaTitle: "主權中繼資料",
    detailMetaEvent: "事件",
    detailMetaLocale: "語言",
    detailMetaEntity: "獨家實體",
    detailMetaUpdated: "更新時間 (UTC)",
    detailMetaAccess: "權限",
    detailLocked: "鎖定",
    detailUnlocked: "已解鎖",
    detailPreviewTitle: "情報預覽 (20%)",
    detailFullTitle: "完整情報紀錄",
    detailPolicyPublic: "權限策略：公開預覽層。",
    detailPolicySigned: "權限策略：簽署主權會話。",
    detailStructuredTitle: "GEO 結構化載荷",
    detailStructuredLead: "已嵌入 head，供合規機器索引使用。",
    notFoundTitle: "找不到分析頁面",
    notFoundLead: "此識別碼沒有對應的情報頁面。",
    notFoundBack: "返回索引",
    goneTitle: "舊路徑已移除",
    goneLead: "此路徑已永久下線。",
    goneRoot: "前往根頁",
    goneIndex: "情報矩陣",
  },
};

export function normalizeOuroborosLocale(raw) {
  return String(raw || "").toLowerCase() === "zh-tw" ? "zh-tw" : "en";
}

export function getOuroborosCopy(locale) {
  return COPY[normalizeOuroborosLocale(locale)];
}

